local hsl = require("lush.hsl")

local darkbg_red = hsl("#FF0000")
local darkbg_green = hsl("#00FF00")
local darkbg_yellow = hsl("#FFFF00")
local darkbg_blue = hsl("#0000FF")
local darkbg_purple = hsl("#7700FF")
local darkbg_aqua = hsl("#00FFFF")
local darkbg_orange = hsl("#FF7700")
local darkbg_magenta = hsl("#FF00FF")
local dark0_hard = hsl("#201020")
local dark0 = hsl("#301030")
local dark0_soft = hsl("#302030")
local light0_hard = hsl("#EEDDDD")
local light0 = hsl("#E0DFDF")
local light0_soft = hsl("#E3DDDD")

-- lush_jsx palette
return {
	dark0_hard = dark0_hard,
	dark0 = dark0,
	dark0_soft = dark0_soft,
	dark1 = dark0.lighten(5),
	dark2 = dark0.lighten(10),
	dark3 = dark0.lighten(15),
	dark4 = dark0.lighten(20),
	light0_hard = light0_hard,
	light0 = light0,
	light0_soft = light0_soft,
	light1 = light0.lighten(5),
	light2 = light0.lighten(10),
	light3 = light0.lighten(15),
	light4 = light0.lighten(20),
	darkbg_red = darkbg_red,
	darkbg_green = darkbg_green,
	darkbg_yellow = darkbg_yellow,
	darkbg_blue = darkbg_blue,
	darkbg_purple = darkbg_purple,
	darkbg_aqua = darkbg_aqua,
	darkbg_orange = darkbg_orange,
	darkbg_magenta = darkbg_magenta,
	neutral_red = darkbg_red.darken(21),
	neutral_green = darkbg_green.darken(21),
	neutral_yellow = darkbg_yellow.darken(21),
	neutral_blue = darkbg_blue.darken(21),
	neutral_purple = darkbg_purple.darken(21),
	neutral_aqua = darkbg_aqua.darken(21),
	neutral_orange = darkbg_orange.darken(21),
	neutral_magenta = darkbg_magenta.darken(21),
	lightbg_red = darkbg_red.darken(37).saturate(50),
	lightbg_green = darkbg_green.darken(37).saturate(50),
	lightbg_yellow = darkbg_yellow.darken(37).saturate(50),
	lightbg_blue = darkbg_blue.darken(37).saturate(50),
	lightbg_purple = darkbg_purple.darken(37).saturate(50),
	lightbg_aqua = darkbg_aqua.darken(37).saturate(50),
	lightbg_orange = darkbg_orange.darken(37).saturate(50),
	lightbg_magenta = darkbg_magenta.darken(37).saturate(50),
	error = hsl("#ff1319"),
	gray = hsl("#9a9a9a"),
}
